# NUMPY

In [1]:
# Semplice import della libreria da utilizzare
import numpy as np 

In [10]:
# Dichiarazione di un array tramite numpy
A = np.array([1,2,3,4,5,6])

In [18]:
# Dichiarazione di una matrice
M = np.array([[1,2,3],[4,5,6]])

In [20]:
# Per l'accesso ai singoli elementi si possono sfruttare gli indici della matrice
a = M[0,2] # Prelevo l'elemento della prima riga presente al 3 posto
print(a)

3


In [ ]:
# Si possono estrarre anche delle sottomatrici, da cui
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = A[1:3,0:2] # 1:3 indica il range 1-2 delle righe, mentre 0:2 indica il range 0-1 delle colonne
print(D)

[[4 5]
 [7 8]]


In [32]:
# Talvolta può interessarmi memorizzare i dati in un certo tipo di modo, per cui:
A = np.array([1,2,3], dtype=np.float32)
# Dove i tipi che sono effettivamente utilizzati sono: uint8, int64, float32, float64, complex64, bool
# Quando dichiaro tali tipologie di dato devono essere sempre precedute da np. per identificare la libreria

# Se invece desidero cambiare la tipologia di interpretazione vado ad utilizzare la funzione
A.astype(np.int16)

array([1, 2, 3], dtype=int16)

# Comandi di utilità generale

In [34]:
righe = 2
colonne = 3

 ### Matrice di zeri

In [ ]:
# Matrice NxM (righe x colonne) di tutti 0
Z = np.zeros((righe,colonne)) # se non specificato saranno interpretato con dtype float64
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]]


### Matrice di uno

In [36]:
U = np.ones((righe, colonne))
print(U) # -> se non specificato dtype = float64

[[1. 1. 1.]
 [1. 1. 1.]]


### Copia di una matrice

In [37]:
C = np.copy(U)
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]


### Matrice Identica

In [39]:
I = np.eye(righe)
print(I)

[[1. 0.]
 [0. 1.]]


### Arange

In [ ]:
# Definizione di un vettore di elementi che vanno da 0 a N - 1, dove N è specificato nella funzione
K = np.arange(10)
print(K)

[0 1 2 3 4 5 6 7 8 9]


### Trasposta

In [47]:
B = U.T
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Affiancamento di matrici

In [52]:
ZU = np.hstack((Z,U))
print(ZU)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


### Sovrapposizione di Matrici

In [53]:
ZU = np.vstack((Z,U))
print(ZU)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Operazioni sugli array

In [73]:
# Visualizzazione del dtype di una matrice
print(Z.dtype)

# Numero di elementi lungo ogni dimensione
print(Z.shape)

# Numero di dimensioni dell'array, se matrice 2 se vettore 1 ecc.
print(Z.ndim)

# Numero totale di elementi dell'array
print(Z.size)

# numero di elementi lungo la prima dimensione (righe)
print(len(Z))

# Ordine delle colonne/righe invertito
print(M) # Matrice originale
print(M[:,::-1]) # colonne invertite
print(M[::-1,:]) # righe invertite

# Funzioni matematiche punto punto (cos, abs, log, exp)
print(np.cos(M)) # Calcolo del coseno punto punto

# Calcolo del minimo/massimo (min,max)
print(np.min(M))

# Calcolo del minimo per ogni colonna -> 0, riga -> 1
print(np.max(M,0))
print(np.max(M,1))

# Concatenamento delle righe/ delle colonne
print(M.flatten(order='C')) # concatena le righe
print(M.flatten(order='F')) # concatena le colonne

# Salvataggio dei dati
np.save('prova.npy', M)

# Caricamento dei dati
K = np.load('prova.npy')

float64
(2, 3)
2
6
2
[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
1
[4 5 6]
[3 6]
[1 2 3 4 5 6]
[1 4 2 5 3 6]
